### ISSUE TITLE
Finalize tech stack and research techs

### ISSUE THREAD

**Issue by arethashwalls** [arethashwalls/QuestProject#3]

**Comment by ac5599656** [comment]
JWT- JSON Web Token creates token for each user to verify and authenticate API call coming from the same user. 
https://medium.com/vandium-software/5-easy-steps-to-understanding-json-web-tokens-jwt-1164c0adfcec

Paper.js - function just like Adobe Illustrator and Adobe Photoshop. I wonder if this would useful in terms of creating task.  My main concern with this technology would it be too complex for the user?
Joint.js- allows users to create basic shapes.  I thought this would be useful in terms for creating tasks and timeline.
Gojs- creates diagrams across modern browser and platform.  There are several features that this Javascript library has such as drag and drop, copy and paste, transactional state and undo management, verviews, data-bound models, event handlers, and an extensible tool system for custom operations. It also provides 150 interactive samples. https://modeling-languages.com/gojs-javascript-library-build-diagrams/
Here are also a bunch we can also implement that Aretha mentions in the team slack: https://modeling-languages.com/javascript-drawing-libraries-diagrams/
Bouncing down Arrow https://codepen.io/dodozhang21/pen/siKtp
Another Arrow:
https://www.solodev.com/blog/web-design/adding-a-scroll-down-anchor-to-your-website.stml
http://jossmac.github.io/react-images/
Lightbox React
