### ISSUE TITLE
Create User collection and setup authentification

### ISSUE THREAD

**Issue by arethashwalls** [arethashwalls/QuestProject#7]
Users should at a minimum have the following fields:
* username: string, required
* password: string, required, set a min length
* a reference to Quests by id

Users will require the following routes:
* GET user/:id to get specific user
* POST user to create new user
* Whatever else is required by authentification needs

Users should have sessions with JWT tokens

We'll need forms for creating users and for logging on.

**Comment by ac5599656** [comment]
Completed user authentication and created  a model for User in Mongoose!
